// used for projection and view matrix
#define BASE_BINDING_POINT_IDX 0
#define PBR_BINDING_POINT_IDX 1
#define LIGHTS_BINDING_POINT_IDX 2
#define PHONG_BINDING_POINT_IDX 3
#define SOLID_BINDING_POINT_IDX 4
#define SPECULAR_GLOSSINESS_BINDING_POINT_IDX 5
